name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Demo Application
        run: |
          npm install
          npm run dev &  # Start the app in the background
    
      - name: Verify Application is Running
        run: curl --fail http://localhost:5173 || (cat demo-app/app.log && exit 1)

      - name: Install Playwright Dependencies
        run: |
          echo "Current directory: $(pwd)"  # Print the current working directory
          ls -lah  # List all files to confirm we're in the right repo
          npx playwright install chromium
          npm install -g allure-commandline --save-dev

      - name: Run Playwright Tests
        run: npx playwright test
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:5173

      - name: Check Allure Results
        run: ls -R reports/allure-results

      - name: Generate Allure Report
        run: allure generate reports/allure-results --clean -o allure-report
      
      - name: Check Allure Report
        run: ls -R allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: success() || failure()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: allure-report
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 7
